### ISSUE TITLE
Create Semantic UI Responsive Menu Package

### ISSUE THREAD

**Issue by justinr1234** [justinr1234/opinionated-meteor-application-template#4]
Create a dynamic menu component similar to: https://github.com/meteor-utilities/menu

But which uses Semantic UI menus: https://semantic-ui.com/collections/menu.html

And has a better approach / is responsive.

- Responsive
- Semantic UI
- Could work similar to https://github.com/richsilv/semantic-ui-modal/
- Could work similar to https://github.com/meteor-utilities/menu

**Comment by nealgist** [comment]
Hey man if it's possible could you please assign this issue to me? I'm not seeing any options to do it from my end.
